Convert slash command data into a job factory instaed of just a dictionary
sBuiltaJr/imageGenSD pull request #10
Opened 2024-02-24 18:44 UTC by sBuiltaJr

This PR converts all slash commands using the job queue into a factory.  The factory removes special handling for certain kinds of jobs and will enable easier command expansion/integration in the future.

See the changelog for a more detailed description.

2024-02-24 21:59 UTC, Mizuko requested changes
Consider a unified way to generate post/embed formatting, so Roll and ShowProfile don't have redundant code.

2024-02-24 21:59 UTC, Mizuko commented on imageGenSD.py
> +        """job = { 'metadata' : {
Dead code in comment to be removed

2024-02-24 21:59 UTC, Mizuko commented on src/managers/QueueMgr.py
> +        if request.GetGuild() not in jobs:#request['data']['guild'] not in jobs:
Dead code in comment to be removed

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/TagRandomizer.py
>          for word in range(0, tag_count):
Fix indentation on `for` block from 13 spaces to 12 spaces

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/JobFactory.py
> +#encapsualtes different job types and post functions based on the specific
"Encapsulates"

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/JobFactory.py
> +#####  Abstract Casses  #####
"Classes"

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/JobFactory.py
> +           Output: bool - Whether or not the job needs ranomized tags added.
"randomized"

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/JobFactory.py
> +#####  Enum Casses  #####
"Classes"

2024-02-24 21:59 UTC, Mizuko commented on src/utilities/JobFactory.py
> +#####  Job Casses  #####
"Classes"

2024-02-25 16:47 UTC, sBuiltaJr commented on src/managers/QueueMgr.py
> +        if request.GetGuild() not in jobs:#request['data']['guild'] not in jobs:
Corrected.

2024-02-28 05:57 UTC, Mizuko approved these changes

2024-02-28 22:18 UTC, merged